@startuml

actor Engineer as user
participant "Source Code Repo" as git
participant "Continuous Integration Tool" as cicd
participant "Container Repo" as dckr
participant "Bootstrap Console" as cnsl
participant "Hosting Environment" as clstr

user -> git : Commits source code
git <- cicd : Listens for commits

== Software Build-time ==

cicd <- cicd : Build source code
cicd <- cicd : Run tests
cicd <- cicd : Build container
cicd -> dckr : Persist container

== Software Deploy-time ==

user -> cnsl : CMD | $ deploy-container...
cnsl -> dckr : Download conatiner
cnsl -> clstr : Deploy container

== Software Runtime == 

@enduml